apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskproject
  template:
    metadata:
      labels:
        app: flaskproject
    spec:
      containers:
      - name: flaskproject
        image: flaskproject:latest
        ports:
        - containerPort: 5000
